print("my name is Collins")
print("a am 18 years old")
print("i come from Nairobi county")
print("i love skating,watching,plaing games")
print("--------------")
print("***************")
print("##------##")